assembly-versioning-scheme: Major
next-version: 4.0
commit-message-incrementing: Disabled
branches:
  develop:
    tag: alpha
    prevent-increment-of-merged-branch-version: true
  releases?[/-]:
    tag: rc
    prevent-increment-of-merged-branch-version: true    
disabled-base-version-strategies:
  - MergeMessageBaseVersionStrategy
