assembly-versioning-scheme: Major
next-version: 4.0
commit-message-incrementing: Disabled
branches:
  develop:
    tag: alpha
    prevent-increment-of-merged-branch-version: true
  releases?[/-]:
    tag: rc
    prevent-increment-of-merged-branch-version: true
ignore:
  sha:
    - efe8a7a49fd589fb497821b98124dc28c670d8d2